In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])
print("Original array:", x)

Original array: [1 2 3 4 5]


In [3]:
x = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
x = np.zeros((3, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
x = np.ones((2, 3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
X = np.full((2, 3), 7)
print(X)

[[7 7 7]
 [7 7 7]]


In [7]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
x = np.empty((2, 3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
print("Array X = \n", x)
print("Array Y = \n", y)
x + y

Array X = 
 [[1 2 3]
 [4 5 6]]
Array Y = 
 [[ 7  8  9]
 [10 11 12]]


array([[ 8, 10, 12],
       [14, 16, 18]])

In [10]:
#sum of all elements of given array
np.sum(x)

21

In [11]:
np.sum(x,axis=0)  # Sum of each column
np.sum(x,axis=1)  # Sum of each row
print("Coloumn Wise Sum = ", np.sum(x,axis=0))
print("Row Wise Sum = ", np.sum(x,axis=1))

Coloumn Wise Sum =  [5 7 9]
Row Wise Sum =  [ 6 15]


In [12]:
#sum of array x & y
np.sum(x + y)

78

In [13]:
x = np.array([10,25,96,87,32,45,26,12,45,85,96,14,36,48,59])
x

array([10, 25, 96, 87, 32, 45, 26, 12, 45, 85, 96, 14, 36, 48, 59])

In [14]:
print("Mean = ", x.mean())
print("Median = ", np.median(x))


Mean =  47.733333333333334
Median =  45.0


In [15]:
minofx = np.min(x)
maxofx = np.max(x)
print("Minimum value in x = ", minofx)
print("Maximum value in x = ", maxofx)
x.size

Minimum value in x =  10
Maximum value in x =  96


15

In [16]:
a = np.array([1,2,3,4,5,6])
print("Array a = ", a)

Array a =  [1 2 3 4 5 6]


In [17]:
#starting index is included and ending index is excluded
a[0:]
a[1:]
a[:4]
a[1:5]
a[:1000] #if ending index is more than size of array, it will consider upto last index only

array([1, 2, 3, 4, 5, 6])

In [18]:
a[::2] #every 2nd element

array([1, 3, 5])

Reshape Of an Array

In [19]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
a.shape

(20,)

In [21]:
a.reshape(4,5) #2d array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
a.reshape(5, 2, 2)  #3d array

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [23]:
a.reshape(-1,4)  #automatically calculates number of rows
a.reshape(2,-1)  #automatically calculates number of columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

Flatten Array - 
Converts all multi dimensional array to 1-d array

In [24]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
a.flatten()  #converts multi-dim array to 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
a.flatten(order='F')  #column-wise flattening

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [27]:
a.flatten(order='C')  #row-wise flattening

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.flatten(order='K') #as per memory layout

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])