🔢 NumPy Practice Questions (Medium Level)

In [8]:
import numpy as np

1. Array Creation
Create a NumPy array of numbers from 1 to 20. Then print its size.

In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)


2. Zeros & Ones
Create:

(a) 3×4 array filled with zeros

(b) 2×5 array filled with ones

In [10]:
#(a)
arr = np.zeros(12).reshape(3,4)
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
#(b)
arr = np.ones(10).reshape(2,5)
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


3. Full Function
Create a 4×4 array where every value is 7 using NumPy

In [15]:
arr = np.full((4,4), 7, dtype = int)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


4. Reshape
Create an array from 1 to 12 and reshape it into:

3×4

2×6

In [18]:
arr = np.arange(1,13)
print(arr)
print("Reshaped into 3x4 : \n", arr.reshape(3,4))
print("Reshaped into 2x6 : \n", arr.reshape(2,6))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped into 3x4 : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped into 2x6 : 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


5. Flatten
Take a 3×3 matrix and convert it into a 1D array using flatten.

In [21]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
print("Flattened Array : ", arr.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened Array :  [1 2 3 4 5 6 7 8 9]


6. Arrange (arange)
Create an array starting from 10 to 50 with a step of 5.

In [23]:
arr = np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


7. Sum of Elements
Given array:
[10, 20, 30, 40, 50]
Find:

total sum & sum of first 3 elements only

In [26]:
arr = np.arange(10,51,10)
print(arr)
print("Total Sum = ", np.sum(arr))
print("Sum of first 3 elements = ", np.sum(arr[:3]))

[10 20 30 40 50]
Total Sum =  150
Sum of first 3 elements =  60


8. Matrix Addition
Add the following two arrays:

A = [[1,2,3],
     [4,5,6]]


B = [[6,5,4],
     [3,2,1]]

In [29]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[6,5,4],[3,2,1]])
print("A = \n", a)
print("B = \n", b)
print("Matrix Addition = \n", a+b)

A = 
 [[1 2 3]
 [4 5 6]]
B = 
 [[6 5 4]
 [3 2 1]]
Matrix Addition = 
 [[7 7 7]
 [7 7 7]]


9. Matrix Subtraction
Subtract array B from array A (from Q8)

In [30]:
print("Matrix Subtraction = \n", a-b)

Matrix Subtraction = 
 [[-5 -3 -1]
 [ 1  3  5]]


10. Element-wise Multiplication
Multiply arrays A and B element by element.

In [31]:
print("Matrix multiplition = \n", a*b)

Matrix multiplition = 
 [[ 6 10 12]
 [12 10  6]]


11. Mean
Find the mean of:
[12, 15, 20, 25, 30]

In [33]:
arr = np.array([12,15,20,25,30])
print(arr.mean())

20.4


12. Median
Find the median of:
[5, 2, 9, 1, 7, 6]

In [37]:
arr = np.array([5, 2, 9, 1, 7, 6])
print(np.median(arr))

5.5


13. Standard Deviation
Find the standard deviation of:
[4, 8, 6, 5, 3, 7]

In [38]:
arr = np.array([4,8,6,5,3,7])
print(np.std(arr))

1.707825127659933


14. Row-wise Sum
Given matrix:

[[1,2,3],
 [4,5,6],
 [7,8,9]]

Find sum of each row separately.

In [41]:
arr = np.array([[1,2,3],
 [4,5,6],
 [7,8,9]])
print(arr)
print("Row wise sum = \n", arr.sum(axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row wise sum = 
 [ 6 15 24]


15. Column-wise Sum
Using the same matrix from Q14, find sum of each column.

In [42]:
print("Coloumn wise sum = \n", arr.sum(axis = 0))

Coloumn wise sum = 
 [12 15 18]


16. Reshape + Mean
Create numbers from 1 to 16, reshape into 4×4, then find the mean of each row.

In [45]:
arr = np.arange(1,17)
print(arr)
arr2 = arr.reshape(4,4)
print("Reshaped to 4x4 : \n", arr2)
print("Row wise mean = ", arr2.mean(axis = 1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Reshaped to 4x4 : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise mean =  [ 2.5  6.5 10.5 14.5]


17. Flatten + Size
Create a 5×5 ones matrix. Flatten it and find its size.

In [48]:
arr = np.ones(25).reshape(5,5)
print(arr)
print(arr.shape)
arr2 = arr.flatten()
print("Flattened = ", arr2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(5, 5)
Flattened =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]


18. Arithmetic Combination
Given:
A = [1,2,3,4]
B = [5,6,7,8]

Compute:
(A + B) * 2

In [50]:
a = np.arange(1,5)
b = np.arange(5,9)
print("A = ",a)
print("B = ", b)
arr = (a+b)*2
print("(A + B) * 2 = ", arr)

A =  [1 2 3 4]
B =  [5 6 7 8]
(A + B) * 2 =  [12 16 20 24]


19. Mixed Operations
Create array from 1–9, reshape to 3×3. Multiply entire matrix by 5 and then find total sum.


In [51]:
arr = np.arange(1,10)
print(arr)
arr2 = arr.reshape(3,3)
print(arr2)
arr3 = arr2*5
print("Multiply with 5 = \n", arr3)
print("Total sum = ", arr3.sum())

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Multiply with 5 = 
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Total sum =  225


20. Statistics Combo
Given:
[15, 18, 21, 24, 27, 30]

Find:

mean

median

standard deviation

In [52]:
arr = np.array([15, 18, 21, 24, 27, 30])
print(arr)
print("Mean = ", arr.mean())
print("Median = ", np.median(arr))
print("Standard Deviation = ", np.std(arr))

[15 18 21 24 27 30]
Mean =  22.5
Median =  22.5
Standard Deviation =  5.123475382979799
