🔢 NumPy Practice Questions (Hard Level)

In [1]:
import numpy as np

1. Advanced Reshape + Sum

Create an array from 1 to 48.
Reshape it into 4 × 4 × 3.
Find:

sum along axis 0

sum along axis 1

sum along axis 2


In [3]:
arr = np.arange(1,49)
arr3d = arr.reshape(4,4,3)
print("3D Array = \n", arr3d)
# print("Shape of Array = ", arr3d.shape)

print("Sum along axis 0 = \n", arr3d.sum(axis = 0))
print("Sum along axis 1 = \n", arr3d.sum(axis = 1))
print("Sum along axis 2 = \n", arr3d.sum(axis = 2))

3D Array = 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]
Sum along axis 0 = 
 [[ 76  80  84]
 [ 88  92  96]
 [100 104 108]
 [112 116 120]]
Sum along axis 1 = 
 [[ 22  26  30]
 [ 70  74  78]
 [118 122 126]
 [166 170 174]]
Sum along axis 2 = 
 [[  6  15  24  33]
 [ 42  51  60  69]
 [ 78  87  96 105]
 [114 123 132 141]]



2. Conditional Replacement

Create array from 1 to 20.
Replace all numbers:

divisible by 3 → -1

divisible by 5 → 100

(Do it using NumPy, not loops.)


In [7]:
arr = np.arange(1,21)
print(arr)
#replace all multiples of 3 with -1 and multiples of 5 with 100
arr[(arr % 3 == 0)] = -1
arr[(arr % 5 == 0)] = 100
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   2  -1   4 100  -1   7   8  -1 100  11  -1  13  14  -1  16  17  -1
  19 100]



3. Broadcasting Math

Given:

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])


B = np.array([10,20,30])

Add B to every row of A using broadcasting.


In [9]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])


B = np.array([10,20,30])

result = A.sum(axis=1) + B
print("Resultant Array = ", result)

Resultant Array =  [16 35 54]



4. Flatten vs Ravel Logic

Create a 3×3 matrix.
Use ravel() to flatten and modify the first element.
Then check whether original array changes.
Explain why.



5. Indexing Challenge

Create array 1–25 and reshape to 5×5.
Extract:

middle row

last column

corner elements only



6. Statistical Axis Problem

Given:

arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

Find:

mean of each column

standard deviation of each row



7. Matrix Arithmetic Combo

Create two random 3×3 arrays.
Compute:

(A + B) * 2 - A



8. Pattern Matrix

Create this matrix using NumPy only:

[[1,0,1,0],
 [0,1,0,1],
 [1,0,1,0],
 [0,1,0,1]]

(No manual typing.)



9. 3D Array Stats

Create array from 1–27 and reshape to 3×3×3.
Find:

overall mean

mean along axis 0

median of entire array



10. Multi-step Transformation

Create array from 1–16.
Steps:

Reshape to 4×4

Multiply each column by [1,2,3,4]

Flatten result

Find standard deviation